# Generated by Django 6.0 on 2026-01-03 21:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('section', models.CharField(blank=True, max_length=200)),
                ('tags', models.CharField(blank=True, max_length=500)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('code', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('instructions', models.TextField(blank=True)),
                ('status', models.CharField(blank=True, choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', max_length=20)),
            ],
            options={
                'ordering': ['-date_added', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ComponentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='component_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='html_templates.component')),
            ],
        ),
    ]
